# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_cadastro(object):
    def setupUi(self, tela_cadastro):
        tela_cadastro.setObjectName("tela_cadastro")
        tela_cadastro.resize(800, 600)
        tela_cadastro.setStyleSheet("background-image: url(:/newPrefix/back.jpg);")
        self.centralwidget = QtWidgets.QWidget(tela_cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 320, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.cadastro_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.cadastro_nome.setGeometry(QtCore.QRect(400, 160, 113, 20))
        self.cadastro_nome.setStyleSheet("color: rgb(255, 255, 255);")
        self.cadastro_nome.setObjectName("cadastro_nome")
        self.cadastro_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.cadastro_cpf.setGeometry(QtCore.QRect(400, 220, 113, 20))
        self.cadastro_cpf.setStyleSheet("color: rgb(255, 255, 255);")
        self.cadastro_cpf.setObjectName("cadastro_cpf")
        self.cadastro_numero = QtWidgets.QLineEdit(self.centralwidget)
        self.cadastro_numero.setGeometry(QtCore.QRect(400, 270, 113, 20))
        self.cadastro_numero.setStyleSheet("color: rgb(255, 255, 255);")
        self.cadastro_numero.setObjectName("cadastro_numero")
        self.cadastro_email = QtWidgets.QLineEdit(self.centralwidget)
        self.cadastro_email.setGeometry(QtCore.QRect(400, 320, 113, 20))
        self.cadastro_email.setStyleSheet("color: rgb(255, 255, 255);")
        self.cadastro_email.setObjectName("cadastro_email")
        self.cadastro_endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.cadastro_endereco.setGeometry(QtCore.QRect(400, 380, 113, 20))
        self.cadastro_endereco.setStyleSheet("color: rgb(255, 255, 255);")
        self.cadastro_endereco.setObjectName("cadastro_endereco")
        self.botao_cadastrar = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.botao_cadastrar.setGeometry(QtCore.QRect(340, 450, 111, 41))
        self.botao_cadastrar.setStyleSheet("color: rgb(85, 255, 255);")
        self.botao_cadastrar.setObjectName("botao_cadastrar")
        self.botao_ja_possuo_cadastro = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.botao_ja_possuo_cadastro.setGeometry(QtCore.QRect(10, 550, 185, 41))
        self.botao_ja_possuo_cadastro.setStyleSheet("color: rgb(85, 255, 255);")
        self.botao_ja_possuo_cadastro.setObjectName("botao_ja_possuo_cadastro")
        tela_cadastro.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_cadastro)
        QtCore.QMetaObject.connectSlotsByName(tela_cadastro)

    def retranslateUi(self, tela_cadastro):
        _translate = QtCore.QCoreApplication.translate
        tela_cadastro.setWindowTitle(_translate("tela_cadastro", "MainWindow"))
        self.label.setText(_translate("tela_cadastro", "Faça seu cadastro"))
        self.label_2.setText(_translate("tela_cadastro", "Nome:"))
        self.label_3.setText(_translate("tela_cadastro", "Cpf:"))
        self.label_4.setText(_translate("tela_cadastro", "Número:"))
        self.label_5.setText(_translate("tela_cadastro", "Email:"))
        self.label_6.setText(_translate("tela_cadastro", "Endereço:"))
        self.botao_cadastrar.setText(_translate("tela_cadastro", "Cadastrar"))
        self.botao_ja_possuo_cadastro.setText(_translate("tela_cadastro", "Já possuo cadastro!"))
import background


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_cadastro = QtWidgets.QMainWindow()
    ui = Ui_tela_cadastro()
    ui.setupUi(tela_cadastro)
    tela_cadastro.show()
    sys.exit(app.exec_())
