# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_produto.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_produto(object):
    def setupUi(self, tela_produto):
        tela_produto.setObjectName("tela_produto")
        tela_produto.resize(800, 392)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(False)
        tela_produto.setFont(font)
        tela_produto.setStyleSheet("background-image: url(:/newPrefix/back.jpg);")
        self.centralwidget = QtWidgets.QWidget(tela_produto)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 150, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 190, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 230, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.produto_id = QtWidgets.QLineEdit(self.centralwidget)
        self.produto_id.setGeometry(QtCore.QRect(420, 150, 113, 20))
        self.produto_id.setStyleSheet("color: rgb(255, 255, 255);")
        self.produto_id.setObjectName("produto_id")
        self.produto_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.produto_nome.setGeometry(QtCore.QRect(420, 190, 113, 20))
        self.produto_nome.setStyleSheet("color: rgb(255, 255, 255);")
        self.produto_nome.setObjectName("produto_nome")
        self.produto_valor = QtWidgets.QLineEdit(self.centralwidget)
        self.produto_valor.setGeometry(QtCore.QRect(420, 230, 113, 20))
        self.produto_valor.setStyleSheet("color: rgb(255, 255, 255);")
        self.produto_valor.setObjectName("produto_valor")
        self.botao_cadastrar_produto = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.botao_cadastrar_produto.setGeometry(QtCore.QRect(310, 280, 151, 41))
        self.botao_cadastrar_produto.setStyleSheet("color: rgb(85, 255, 255);")
        self.botao_cadastrar_produto.setObjectName("botao_cadastrar_produto")
        self.botao_voltar_login = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_login.setGeometry(QtCore.QRect(10, 360, 75, 23))
        self.botao_voltar_login.setStyleSheet("color: rgb(85, 255, 255);")
        self.botao_voltar_login.setObjectName("botao_voltar_login")
        tela_produto.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_produto)
        QtCore.QMetaObject.connectSlotsByName(tela_produto)

    def retranslateUi(self, tela_produto):
        _translate = QtCore.QCoreApplication.translate
        tela_produto.setWindowTitle(_translate("tela_produto", "Cadastrar Produto"))
        self.label.setText(_translate("tela_produto", "Cadastrar Produto"))
        self.label_2.setText(_translate("tela_produto", "ID do Produto:"))
        self.label_3.setText(_translate("tela_produto", "Nome do Produto:"))
        self.label_4.setText(_translate("tela_produto", "Valor do Produto:"))
        self.botao_cadastrar_produto.setText(_translate("tela_produto", "Cadastrar Produto"))
        self.botao_voltar_login.setText(_translate("tela_produto", "Login"))
import background


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_produto = QtWidgets.QMainWindow()
    ui = Ui_tela_produto()
    ui.setupUi(tela_produto)
    tela_produto.show()
    sys.exit(app.exec_())
