# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_login(object):
    def setupUi(self, tela_login):
        tela_login.setObjectName("tela_login")
        tela_login.setEnabled(True)
        tela_login.resize(692, 307)
        tela_login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        tela_login.setAutoFillBackground(False)
        tela_login.setStyleSheet("background-image: url(:/newPrefix/back.jpg);")
        tela_login.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(tela_login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(240, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 150, 113, 20))
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(85, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 280, 75, 23))
        self.pushButton_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(310, 190, 81, 41))
        self.commandLinkButton.setMouseTracking(True)
        self.commandLinkButton.setStyleSheet("color: rgb(85, 255, 255);")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(580, 260, 111, 41))
        self.commandLinkButton_2.setAutoFillBackground(False)
        self.commandLinkButton_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 120, 113, 20))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        tela_login.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_login)
        QtCore.QMetaObject.connectSlotsByName(tela_login)

    def retranslateUi(self, tela_login):
        _translate = QtCore.QCoreApplication.translate
        tela_login.setWindowTitle(_translate("tela_login", "Login"))
        self.label.setText(_translate("tela_login", "Login:"))
        self.label_2.setText(_translate("tela_login", "Senha:"))
        self.label_3.setText(_translate("tela_login", "LelaByteShop"))
        self.pushButton_2.setText(_translate("tela_login", "Vendedor"))
        self.commandLinkButton.setText(_translate("tela_login", "Entrar"))
        self.commandLinkButton_2.setText(_translate("tela_login", "Cadastrar"))
import background


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_login = QtWidgets.QMainWindow()
    ui = Ui_tela_login()
    ui.setupUi(tela_login)
    tela_login.show()
    sys.exit(app.exec_())
