# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_principal(object):
    def setupUi(self, tela_principal):
        tela_principal.setObjectName("tela_principal")
        tela_principal.resize(1062, 842)
        font = QtGui.QFont()
        font.setPointSize(20)
        tela_principal.setFont(font)
        tela_principal.setStyleSheet("color: rgb(85, 255, 255);\n"
"background-image: url(:/newPrefix/back.jpg);")
        self.centralwidget = QtWidgets.QWidget(tela_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.mostrar_nome_usuario = QtWidgets.QLabel(self.centralwidget)
        self.mostrar_nome_usuario.setGeometry(QtCore.QRect(510, 240, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mostrar_nome_usuario.setFont(font)
        self.mostrar_nome_usuario.setObjectName("mostrar_nome_usuario")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.botao_finalizar_compra = QtWidgets.QPushButton(self.centralwidget)
        self.botao_finalizar_compra.setGeometry(QtCore.QRect(460, 530, 101, 51))
        self.botao_finalizar_compra.setObjectName("botao_finalizar_compra")
        self.lista_produtos = QtWidgets.QListWidget(self.centralwidget)
        self.lista_produtos.setGeometry(QtCore.QRect(20, 220, 311, 601))
        self.lista_produtos.setObjectName("lista_produtos")
        self.lista_carrinho = QtWidgets.QListWidget(self.centralwidget)
        self.lista_carrinho.setGeometry(QtCore.QRect(670, 220, 341, 601))
        self.lista_carrinho.setObjectName("lista_carrinho")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 400, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mostrar_valor_total = QtWidgets.QLabel(self.centralwidget)
        self.mostrar_valor_total.setGeometry(QtCore.QRect(490, 450, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mostrar_valor_total.setFont(font)
        self.mostrar_valor_total.setObjectName("mostrar_valor_total")
        self.botao_sair = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.botao_sair.setGeometry(QtCore.QRect(980, 10, 71, 41))
        self.botao_sair.setObjectName("botao_sair")
        tela_principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_principal)
        QtCore.QMetaObject.connectSlotsByName(tela_principal)

    def retranslateUi(self, tela_principal):
        _translate = QtCore.QCoreApplication.translate
        tela_principal.setWindowTitle(_translate("tela_principal", "LelaByteShop"))
        self.label.setText(_translate("tela_principal", "LelaByteShop"))
        self.label_2.setText(_translate("tela_principal", "Bem vindo, "))
        self.mostrar_nome_usuario.setText(_translate("tela_principal", "Lela"))
        self.label_4.setText(_translate("tela_principal", "Produtos disponiveis"))
        self.label_5.setText(_translate("tela_principal", "Carrinho"))
        self.botao_finalizar_compra.setText(_translate("tela_principal", "Finalizar compra"))
        self.label_6.setText(_translate("tela_principal", "Valor Total: "))
        self.mostrar_valor_total.setText(_translate("tela_principal", "1355"))
        self.botao_sair.setText(_translate("tela_principal", "Sair!"))
import background


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_principal = QtWidgets.QMainWindow()
    ui = Ui_tela_principal()
    ui.setupUi(tela_principal)
    tela_principal.show()
    sys.exit(app.exec_())
