# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vendedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_vendedor(object):
    def setupUi(self, tela_vendedor):
        tela_vendedor.setObjectName("tela_vendedor")
        tela_vendedor.resize(540, 223)
        tela_vendedor.setStyleSheet("background-image: url(:/newPrefix/back.jpg);")
        self.centralwidget = QtWidgets.QWidget(tela_vendedor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 100, 81, 41))
        self.label_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.vendedor_codigo = QtWidgets.QLineEdit(self.centralwidget)
        self.vendedor_codigo.setGeometry(QtCore.QRect(240, 110, 211, 20))
        self.vendedor_codigo.setStyleSheet("color: rgb(255, 255, 255);")
        self.vendedor_codigo.setObjectName("vendedor_codigo")
        self.botao_vendedor = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.botao_vendedor.setGeometry(QtCore.QRect(240, 150, 71, 41))
        self.botao_vendedor.setStyleSheet("color: rgb(85, 255, 255);")
        self.botao_vendedor.setObjectName("botao_vendedor")
        tela_vendedor.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_vendedor)
        QtCore.QMetaObject.connectSlotsByName(tela_vendedor)

    def retranslateUi(self, tela_vendedor):
        _translate = QtCore.QCoreApplication.translate
        tela_vendedor.setWindowTitle(_translate("tela_vendedor", "Área do vendedor"))
        self.label.setText(_translate("tela_vendedor", "Área do vendedor"))
        self.label_2.setText(_translate("tela_vendedor", "Digite o Código\n"
" do Funcionário:"))
        self.botao_vendedor.setText(_translate("tela_vendedor", "Entrar"))
import background


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_vendedor = QtWidgets.QMainWindow()
    ui = Ui_tela_vendedor()
    ui.setupUi(tela_vendedor)
    tela_vendedor.show()
    sys.exit(app.exec_())
